name: CI/CD/CT

on: [push] #specifies the event that should trigger the workflow (e.g., on: push).

jobs: # specify the specific jobs that should be run as part of the workflow 
  build:
    runs-on: ubuntu-latest
    steps: # For each job, you can specify the steps that should be run 
    - uses: actions/checkout@v2
    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: 3.8
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Run tests
      run: |
        pytest
    - name: Build Docker image
      run: |
        docker build -t khabdrick/ci_cd_ct:v1 .
    - name: Push Docker image to registry
      run: |
        docker login -u khabdrick -p Muhammed-1998
        docker push khabdrick/ci_cd_ct:v1
